apiVersion: batch/v1
kind: Job
metadata:
  name: service-inject-kaiju
spec:
  template:
    spec:
      containers:
        - name: service-inject-kaiju
          image: kaiju/service-inject-kaiju:latest
          volumeMounts:
            - name: in-volume
              mountPath: /kaiju_data/in
            - name: out-volume
              mountPath: /kaiju_data/out
      volumes:
        - name: in-volume
          hostPath:
            path: ${KAIJU_BASE_PATH}/kaiju_data/chipped
        - name: out-volume
          hostPath:
            path: ${KAIJU_BASE_PATH}/kaiju_data/injected
      restartPolicy: Never