apiVersion: batch/v1
kind: Job
metadata:
  name: service-get-satellite-imagery
spec:
  template:
    spec:
      containers:
        - name: service-get-satellite-imagery
          image: kaiju/service-get-satellite-imagery:latest
          volumeMounts:
            - name: config-volume
              mountPath: /kaiju_data/config
            - name: in-volume
              mountPath: /kaiju_data/in
      volumes:
        - name: config-volume
          hostPath:
            path: ${KAIJU_BASE_PATH}/kaiju_data/config
        - name: in-volume
          hostPath:
            path: ${KAIJU_BASE_PATH}/kaiju_data/in
      restartPolicy: Never