apiVersion: batch/v1
kind: Job
metadata:
  name: service-get-bounding-box
spec:
  template:
    spec:
      containers:
        - name: service-get-bounding-box
          image: kaiju/service-get-bounding-box:latest
          volumeMounts:
            - name: config-volume
              mountPath: /kaiju_data/config
      volumes:
        - name: config-volume
          hostPath:
            path: ${KAIJU_BASE_PATH}/kaiju_data/config
      restartPolicy: Never