FROM kaiju/kaiju-base:0.0.1
USER root
RUN mkdir -p /data
RUN mkdir -p /data/in
RUN mkdir -p /data/config
COPY ./data/config /data/config

RUN mkdir /src
COPY ./src /src

RUN pip3 install --user -r ./src/requirements.txt

CMD ["python", "./src/get_imagery.py"]