apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaiju-workflow-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: get-bounding-box
        template: apply-get-bounding-box
      - name: get-satellite-imagery
        template: apply-get-satellite-imagery
      - name: convert-images
        template: apply-convert-images
      - name: resize-images
        template: apply-resize-images
      - name: chip-images
        template: apply-chip-images
      - name: inject-kaiju
        template: apply-inject-kaiju

  - name: get-bounding-box
    container:
      - image: kaiju/service-get-bounding-box:latest
        volumeMounts:
        - name: config-volume
          mountPath: /kaiju_data/config
    volumes:
      - name: config-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/config

  - name: get-satellite-imagery
    container:
      - image: kaiju/service-get-satellite-imagery:latest
        volumeMounts:
          - name: config-volume
            mountPath: /kaiju_data/config
          - name: in-volume
            mountPath: /kaiju_data/in
    volumes:
      - name: config-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/config
      - name: in-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/in

  - name: convert-images
    container:
      - image: kaiju/service-convert-images:latest
        volumeMounts:
          - name: in-volume
            mountPath: /kaiju_data/in
          - name: out-volume
            mountPath: /kaiju_data/out
    volumes:
      - name: in-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/in
      - name: out-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/converted

  - name: resize-images
    container:
      - image: kaiju/service-resize-images:latest
        volumeMounts:
          - name: in-volume
            mountPath: /kaiju_data/in
          - name: out-volume
            mountPath: /kaiju_data/out
    volumes:
      - name: in-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/converted
      - name: out-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/resized

  - name: chip-images
    container:
      - image: kaiju/service-chip-images:latest
        volumeMounts:
          - name: in-volume
            mountPath: /kaiju_data/in
          - name: out-volume
            mountPath: /kaiju_data/out
    volumes:
      - name: in-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/resized
      - name: out-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/chipped

  - name: inject-kaiju
    container:
      - image: kaiju/service-inject-kaiju:latest
        volumeMounts:
          - name: in-volume
            mountPath: /kaiju_data/in
          - name: out-volume
            mountPath: /kaiju_data/out
    volumes:
      - name: in-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/chipped
      - name: out-volume
        hostPath:
          path: ${KAIJU_BASE_PATH}/kaiju_data/injected